// Every type, validator, decoder and Python binding derives from the payload schemas. Never edit their output.
import { execFileSync } from 'node:child_process'
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { Ajv } from 'ajv'
import addFormats from 'ajv-formats'
import standaloneCode from 'ajv/dist/standalone/index.js'
import { compileFromFile } from 'json-schema-to-typescript'
import moment from 'moment-timezone'
import ts from 'typescript'
import definitions from '../contracts/definitions.schema.json' with { type: 'json' }
import metric from '../contracts/project-metric.schema.json' with { type: 'json' }
import review from '../contracts/project-review.schema.json' with { type: 'json' }

const checking = process.argv.includes('--check')
const outputs = new Set<string>()
async function output(file: string, content: string) {
  outputs.add(file)
  if (checking) {
    if (await readFile(file, 'utf8').catch(() => undefined) !== content) throw new Error(`Generation drift: ${file}; run npm run gen`)
  } else await writeFile(file, content)
}

// The maintained package owns IANA names and links, including modern names omitted by some ICU builds.
const zones = {
  $id: new URL('time-zones.schema.json', metric.$id).href,
  $comment: `Generated by scripts/gen-contract.ts from moment-timezone ${moment.tz.version}, IANA tzdata ${moment.tz.dataVersion}. Refresh with npm run gen; never edit.`,
  title: 'IanaTimeZone',
  type: 'string', enum: moment.tz.names(),
}
await output('contracts/time-zones.schema.json', `${JSON.stringify(zones, null, 2)}\n`)
const ajv = new Ajv({ $data: true, code: { source: true } })
addFormats(ajv)
// An annotation for producers and readers: the bound on one encoded payload, which JSON Schema cannot express.
ajv.addKeyword({ keyword: 'maxEncodedBytes', schemaType: 'number' })
ajv.addSchema(zones).addSchema(definitions)

// Each payload: its handwritten schema, and the directory its generated TypeScript lives in.
const payloads = [
  { name: 'metric', file: 'contracts/project-metric.schema.json', schema: metric, typesModule: 'project-metric' },
  { name: 'review', file: 'contracts/project-review.schema.json', schema: review, typesModule: 'project-review' },
]
for (const { name, file, schema, typesModule } of payloads) {
  const directory = `contracts/generated/${name}`
  const banner = `/* Generated from ${file}. Do not edit. */`
  const bound = 'maxEncodedBytes' in schema ? `\n/** The most UTF-8 bytes one encoded payload may take; readers bound their read by it. */\nexport const maxEncodedBytes = ${schema.maxEncodedBytes}\n` : ''
  await mkdir(directory, { recursive: true })
  await output(`${directory}/${typesModule}.d.ts`, await compileFromFile(file, { bannerComment: banner, cwd: 'contracts', maxItems: -1 }))
  await output(`${directory}/validate.cjs`, `${standaloneCode(ajv, ajv.compile(schema))}\n`)
  // This is the only adapter around the library-generated validator: parse external bytes, validate once,
  // expose its schema-derived type. No application module handles untyped JSON or asserts the output type.
  await output(`${directory}/validate.d.cts`, `${banner}
import type { ValidateFunction } from 'ajv'
import type { ${schema.title} } from './${typesModule}.js'
declare const validate: ((value: unknown) => value is ${schema.title}) & Pick<ValidateFunction<${schema.title}>, 'errors'>
export = validate
`)
  await output(`${directory}/decode.ts`, `${banner}
import validate from './validate.cjs'
import type { ErrorObject } from 'ajv'
import type { ${schema.title} } from './${typesModule}.js'
${bound}export function decode(text: string):
  | { status: 'valid'; value: ${schema.title} }
  | { status: 'invalid'; reason: 'syntax' }
  | { status: 'invalid'; reason: 'schema'; issues: Pick<ErrorObject, 'keyword' | 'instancePath'>[] } {
  try {
    const value: unknown = JSON.parse(text)
    return validate(value) ? { status: 'valid', value }
      : { status: 'invalid', reason: 'schema', issues: (validate.errors ?? []).map(({ keyword, instancePath }) => ({ keyword, instancePath })) }
  } catch { return { status: 'invalid', reason: 'syntax' } }
}
`)
  // Installed dependencies cannot rely on Node's source type stripping.
  // Emit both runtime JavaScript and its declaration from the generated adapter.
  const program = ts.createProgram([`${directory}/decode.ts`], {
    target: ts.ScriptTarget.ES2024,
    module: ts.ModuleKind.NodeNext,
    declaration: true,
    strict: true,
    skipLibCheck: true,
    noEmitOnError: true,
  })
  const emitted = new Map<string, string>()
  const result = program.emit(undefined, (emittedFile, content) => { emitted.set(emittedFile, content) })
  const diagnostics = [...ts.getPreEmitDiagnostics(program), ...result.diagnostics]
  if (result.emitSkipped || diagnostics.length) {
    throw new Error(diagnostics.map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')).join('\n'))
  }
  for (const [emittedFile, content] of emitted) await output(emittedFile, content)
}

// Python producers get msgspec structs from the lockfile-pinned datamodel-code-generator, and one encoder:
// msgspec checks every constraint on the exact bytes it returns, so producers never validate by hand.
const pythonModels = execFileSync('uv', ['run', '--frozen', '--quiet', '--only-group', 'dev', 'datamodel-codegen',
  '--input', 'contracts/project-review.schema.json', '--input-file-type', 'jsonschema',
  '--output-model-type', 'msgspec.Struct', '--target-python-version', '3.12', '--formatters', 'builtin',
  '--disable-timestamp', '--use-annotated', '--field-constraints', '--use-standard-collections',
  '--use-union-operator', '--extra-fields', 'forbid', '--use-generic-base-class', '--enum-field-as-literal', 'all', '--snake-case-field', '--use-schema-description',
  '--custom-file-header', '# Generated from contracts/project-review.schema.json by scripts/gen-contract.ts. Do not edit.',
], { encoding: 'utf8' })
await mkdir('python/project_metric_contract', { recursive: true })
await output('python/project_metric_contract/__init__.py', '"""Generated Python bindings of the project contract; see contracts/ for the owning schemas."""\n')
await output('python/project_metric_contract/py.typed', '')
await output('python/project_metric_contract/review.py', `${pythonModels.trimEnd()}

# The producer's one output boundary.
import msgspec  # noqa: E402

MAX_ENCODED_BYTES = ${review.maxEncodedBytes}
"""The most UTF-8 bytes one encoded review may take; the consumer reads no more."""


def encode(review: ${review.title}) -> bytes:
    """Encode a review, or raise msgspec.ValidationError when it breaks the schema or the byte bound."""
    data = msgspec.json.encode(review)
    msgspec.json.decode(data, type=${review.title})
    if len(data) > MAX_ENCODED_BYTES:
        raise msgspec.ValidationError(f"Encoded review takes {len(data)} bytes; the bound is {MAX_ENCODED_BYTES}")
    return data
`)

for (const root of ['contracts/generated', 'python/project_metric_contract']) {
  for (const entry of await readdir(root, { recursive: true, withFileTypes: true })) {
    const path = `${entry.parentPath}/${entry.name}`
    if (entry.isFile() && !entry.parentPath.includes('__pycache__') && !outputs.has(path)) throw new Error(`Superseded generated output: ${path}`)
  }
}
console.log(checking ? 'Contract generation drift: clean' : 'Generated project contract')
