// Both the type and the decoder derive from the same contract. Never edit their output.
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { Ajv } from 'ajv'
import addFormats from 'ajv-formats'
import standaloneCode from 'ajv/dist/standalone/index.js'
import { compileFromFile } from 'json-schema-to-typescript'
import moment from 'moment-timezone'
import ts from 'typescript'
import schema from '../contracts/project-metric.schema.json' with { type: 'json' }

const checking = process.argv.includes('--check')
const outputs = new Set<string>()
async function output(file: string, content: string) {
  outputs.add(file)
  if (checking) {
    if (await readFile(file, 'utf8') !== content) throw new Error(`Generation drift: ${file}; run npm run gen:metric`)
  } else await writeFile(file, content)
}

// The maintained package owns IANA names and links, including modern names omitted by some ICU builds.
const zones = {
  $id: new URL('time-zones.schema.json', schema.$id).href,
  $comment: `Generated by scripts/gen-project-metric.ts from moment-timezone ${moment.tz.version}, IANA tzdata ${moment.tz.dataVersion}. Refresh with npm run gen:metric; never edit.`,
  title: 'IanaTimeZone',
  type: 'string', enum: moment.tz.names(),
}
await output('contracts/time-zones.schema.json', `${JSON.stringify(zones, null, 2)}\n`)
const ajv = new Ajv({ $data: true, code: { source: true } })
addFormats(ajv)
ajv.addSchema(zones)
const validator = ajv.compile(schema)
await mkdir('contracts/generated', { recursive: true })
await output('contracts/generated/project-metric.d.ts', await compileFromFile('contracts/project-metric.schema.json', { bannerComment: '/* Generated from contracts/project-metric.schema.json. Do not edit. */' }))
await output('contracts/generated/validate.cjs', `${standaloneCode(ajv, validator)}\n`)
// This is the only adapter around the library-generated validator: parse external bytes, validate once,
// expose its schema-derived type. No application module handles untyped JSON or asserts the output type.
await output('contracts/generated/validate.d.cts', `/* Generated from contracts/project-metric.schema.json. Do not edit. */
import type { ValidateFunction } from 'ajv'
import type { ${schema.title} } from './project-metric.js'
declare const validate: ((value: unknown) => value is ${schema.title}) & Pick<ValidateFunction<${schema.title}>, 'errors'>
export = validate
`)
await output('contracts/generated/decode.ts', `/* Generated from contracts/project-metric.schema.json. Do not edit. */
import validate from './validate.cjs'
import type { ErrorObject } from 'ajv'
import type { ${schema.title} } from './project-metric.js'
export function decode(text: string):
  | { status: 'valid'; value: ${schema.title} }
  | { status: 'invalid'; reason: 'syntax' }
  | { status: 'invalid'; reason: 'schema'; issues: Pick<ErrorObject, 'keyword' | 'instancePath'>[] } {
  try {
    const value: unknown = JSON.parse(text)
    return validate(value) ? { status: 'valid', value }
      : { status: 'invalid', reason: 'schema', issues: (validate.errors ?? []).map(({ keyword, instancePath }) => ({ keyword, instancePath })) }
  } catch { return { status: 'invalid', reason: 'syntax' } }
}
`)
// Installed dependencies cannot rely on Node's source type stripping.
// Emit both runtime JavaScript and its declaration from the generated adapter.
const program = ts.createProgram(['contracts/generated/decode.ts'], {
  target: ts.ScriptTarget.ES2024,
  module: ts.ModuleKind.NodeNext,
  declaration: true,
  strict: true,
  skipLibCheck: true,
  noEmitOnError: true,
})
const emitted = new Map<string, string>()
const result = program.emit(undefined, (file, content) => { emitted.set(file, content) })
const diagnostics = [...ts.getPreEmitDiagnostics(program), ...result.diagnostics]
if (result.emitSkipped || diagnostics.length) {
  throw new Error(diagnostics.map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')).join('\n'))
}
for (const [file, content] of emitted) await output(file, content)
for (const file of await readdir('contracts/generated')) {
  if (!outputs.has(`contracts/generated/${file}`)) throw new Error(`Superseded generated output: ${file}`)
}
console.log(checking ? 'Project metric generation drift: clean' : 'Generated project metric contract')
